// packages/comark-svelte/src/components/ComarkNode.svelte
<!--
@component
Recursive Comark AST node renderer.

Renders a single `ComarkNode` — either a text string, a native HTML element
(via `<svelte:element>`), or a custom component (via a capitalized variable).

Recurses into children by importing itself. The streaming caret is threaded
through props and only forwarded to the last child at each level, so it
naturally appears inline after the deepest trailing text node.

@example
```svelte
<ComarkNode node={astNode} components={{ alert: Alert }} />
```
-->
<script module lang="ts">
  import type { ComponentManifest as ComarkComponentManifest } from 'comark'
  import { pascalCase } from 'comark/utils'

  const componentCache = new WeakMap<ComarkComponentManifest, Map<string, any>>()

  function isPromiseLike(value: unknown): value is Promise<unknown> {
    return !!value && typeof (value as { then?: unknown }).then === 'function'
  }

  function unwrapComponent(mod: unknown): any {
    return mod && typeof mod === 'object' && 'default' in mod
      ? (mod as { default?: any }).default
      : mod
  }

  function resolveComponent(tag: string, components: Record<string, any>, componentsManifest?: ComarkComponentManifest): any {
    const pascal = pascalCase(tag)
    const Component
      = components[`Prose${pascal}`]
        || components[pascal]
        || components[tag]

    if (Component) {
      return Component
    }
    if (!componentsManifest) {
      return null;
    }

    let cache = componentCache.get(componentsManifest)
    if (!cache) {
      cache = new Map<string, any>()
      componentCache.set(componentsManifest, cache)
    }

    if (!cache.has(tag)) {
      const resolved = componentsManifest(tag)
      if (resolved) {
        cache.set(
          tag,
          isPromiseLike(resolved)
            ? Promise.resolve(resolved).then(unwrapComponent)
            : unwrapComponent(resolved),
        )
      }
    }

    return cache.get(tag) || null
  }
</script>

<script lang="ts">
  import type { ComarkNode as ComarkNodeType, ComponentManifest, NodeRenderData } from 'comark'
  import type { ComponentResolver } from '../types.js'
  import ComarkNode from './ComarkNode.svelte'
  import ComarkComponent from './ComarkComponent.svelte'
  import Resolve from './Resolve.svelte'
  import { resolveAttributes } from 'comark/utils'

  const EMPTY_RENDER_DATA: NodeRenderData = { frontmatter: {}, meta: {}, data: {}, props: {} }

  let {
    node,
    components = {},
    componentsManifest,
    resolver: Resolver = Resolve,
    caretClass = null,
    renderData = EMPTY_RENDER_DATA,
  }: {
    node: ComarkNodeType
    components?: Record<string, any>
    componentsManifest?: ComponentManifest
    resolver?: ComponentResolver
    caretClass?: string | null
    renderData?: NodeRenderData
  } = $props()

  const CARET_TEXT = '\u2009'
  const CARET_STYLE
    = 'background-color: currentColor; display: inline-block; margin-left: 0.25rem; margin-right: 0.25rem; animation: pulse 0.75s cubic-bezier(0.4,0,0.6,1) infinite;'

  const VOID_ELEMENTS = new Set([
    'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input',
    'link', 'meta', 'param', 'source', 'track', 'wbr',
  ])

  interface RenderChild {
    node: ComarkNodeType
    caretClass: string | null
  }

  interface NamedSlot {
    name: string
    children: ComarkNodeType[]
    caretClass: string | null
  }

  function getSlotName(node: ComarkNodeType): string | null {
    if (typeof node === 'string' || !Array.isArray(node) || node[0] !== 'template') {
      return null
    }

    const props = (node.length >= 2 ? node[1] : {}) ?? {}
    if (typeof props.name === 'string' && props.name) {
      return props.name
    }

    for (const key in props) {
      if (key.startsWith('#') && key.length > 1) {
        return key.slice(1)
      }
    }

    return null
  }

  function toRenderChildren(
    sourceChildren: ComarkNodeType[],
    sourceIndex: number,
    totalChildren: number,
    nodeCaretClass: string | null,
  ): RenderChild[] {
    return sourceChildren.map((child, index) => ({
      node: child,
      caretClass: sourceIndex === totalChildren - 1 && index === sourceChildren.length - 1 ? nodeCaretClass : null,
    }))
  }

  let { isText, tag, isVoid, children, Component, componentPromise, mappedProps } = $derived.by(() => {
    let isText = false
    let tag: string | null = null
    let isVoid = false
    let children: ComarkNodeType[] = []
    let Component: any = null
    let componentPromise: Promise<any> | null = null
    let mappedProps: Record<string, any> = {}

    if (typeof node === 'string') {
      return { isText: true, tag, isVoid, children, Component, componentPromise, mappedProps }
    }

    if (!Array.isArray(node) || node.length < 1) {
      return { isText, tag, isVoid, children, Component, componentPromise, mappedProps }
    }

    // Comment nodes have null as the tag
    if (node[0] === null) {
      return { isText, tag, isVoid, children, Component, componentPromise, mappedProps }
    }

    tag = node[0] as string
    isVoid = VOID_ELEMENTS.has(tag)
    const nodeProps: Record<string, any>
      = (node.length >= 2 ? node[1] : {}) ?? {}
    children = node.length > 2 ? (node.slice(2) as ComarkNodeType[]) : []

    const resolvedComponent = resolveComponent(tag, components, componentsManifest)
    if (resolvedComponent instanceof Promise) {
      componentPromise = resolvedComponent
    }
    else {
      Component = resolvedComponent
    }

    // Resolve `:prefix` bindings, then apply Svelte attribute remapping
    // (`className` → `class`).
    const resolved = resolveAttributes(nodeProps, renderData, { parseJson: true })
    for (const k in resolved) {
      if (k === 'className') {
        mappedProps.class = resolved[k]
      }
      else {
        mappedProps[k] = resolved[k]
      }
    }

    return { isText, tag, isVoid, children, Component, componentPromise, mappedProps }
  })

  // Only shadow the parent's `props` scope when the current element has its
  // own attributes. Bare wrappers (`<p>`, `<ul>`, `<li>`, …) must keep the
  // parent's scope so bindings like `{{ props.x }}` reach across them.
  let childrenRenderData = $derived<NodeRenderData>(
    Object.keys(mappedProps).length > 0
      ? { ...renderData, props: mappedProps }
      : renderData,
  )

  let { defaultChildren, namedSlots } = $derived.by(() => {
    const defaultChildren: RenderChild[] = []
    const slots: NamedSlot[] = []

    for (let i = 0; i < children.length; i++) {
      const child = children[i]
      const slotName = getSlotName(child)
      if (slotName) {
        const slotChildren = (child as unknown as ComarkNodeType[]).slice(2) as ComarkNodeType[]
        if (slotName === 'default') {
          defaultChildren.push(...toRenderChildren(slotChildren, i, children.length, caretClass))
        }
        else {
          slots.push({
            name: slotName,
            children: slotChildren,
            caretClass: i === children.length - 1 ? caretClass : null,
          })
        }
      }
      else {
        defaultChildren.push({ node: child, caretClass: i === children.length - 1 ? caretClass : null })
      }
    }

    return { defaultChildren, namedSlots: slots }
  })
</script>

{#snippet renderChildren()}
  {#each defaultChildren as child, i (i)}
    <ComarkNode
      node={child.node}
      {components}
      {componentsManifest}
      resolver={Resolver}
      caretClass={child.caretClass}
      renderData={childrenRenderData}
    />
  {/each}
{/snippet}

{#if isText}
  {node}{#if caretClass !== null}<span
      class={caretClass || undefined}
      style={CARET_STYLE}>{CARET_TEXT}</span
    >{/if}
{:else if Component && namedSlots.length > 0}
  <ComarkComponent
    {Component}
    props={mappedProps}
    {namedSlots}
    {components}
    {componentsManifest}
    resolver={Resolver}
    renderData={childrenRenderData}
  >
    {@render renderChildren()}
  </ComarkComponent>
{:else if Component}
  <Component {...mappedProps}>
    {@render renderChildren()}
  </Component>
{:else if componentPromise && namedSlots.length > 0}
  <ComarkComponent
    {componentPromise}
    props={mappedProps}
    {namedSlots}
    {components}
    {componentsManifest}
    resolver={Resolver}
    renderData={childrenRenderData}
  >
    {@render renderChildren()}
  </ComarkComponent>
{:else if componentPromise}
  <Resolver promise={componentPromise} props={mappedProps}>
    {@render renderChildren()}
  </Resolver>
{:else if isVoid}
  <svelte:element this={tag} {...mappedProps} />
{:else if tag}
  <svelte:element this={tag} {...mappedProps}>
    {@render renderChildren()}
  </svelte:element>
{/if}

// packages/comark-angular/src/components/comark-node.component.ts
import {
  Component,
  Input,
  ChangeDetectionStrategy,
  ViewContainerRef,
  ElementRef,
  Renderer2,
  OnChanges,
  SimpleChanges,
  Type,
  Injector,
  EnvironmentInjector,
  createComponent,
  reflectComponentType,
} from '@angular/core'
import type { ComarkElement, ComarkNode, NodeRenderData } from 'comark'
import { pascalCase, resolveAttributes } from 'comark/utils'

/**
 * Helper to get tag from a ComarkNode
 */
function getTag(node: ComarkNode): string | null {
  if (Array.isArray(node) && node.length >= 1) {
    return node[0] as string
  }
  return null
}

/**
 * Helper to get props from a ComarkNode
 */
function getProps(node: ComarkNode): Record<string, any> {
  if (Array.isArray(node) && node.length >= 2) {
    return (node[1] as Record<string, any>) || {}
  }
  return {}
}

/**
 * Helper to get children from a ComarkNode
 */
function getChildren(node: ComarkNode): ComarkNode[] {
  if (Array.isArray(node) && node.length > 2) {
    return node.slice(2) as ComarkNode[]
  }
  return []
}

/**
 * Resolve a custom component from the components map.
 */
function resolveComponent(tag: string, components: Record<string, Type<any>>): Type<any> | undefined {
  const pascalTag = pascalCase(tag)
  const proseTag = `Prose${pascalTag}`
  return components[proseTag] || components[tag] || components[pascalTag]
}

/** Void (self-closing) HTML elements that must not have children. */
const VOID_ELEMENTS = new Set([
  'area',
  'base',
  'br',
  'col',
  'embed',
  'hr',
  'img',
  'input',
  'link',
  'meta',
  'param',
  'source',
  'track',
  'wbr',
])

/**
 * ComarkNode — recursive component that renders a single Comark AST node.
 *
 * For text nodes, it inserts the text directly.
 * For element nodes, it creates a native DOM element or instantiates
 * a custom Angular component via ViewContainerRef.
 */
@Component({
  selector: 'comark-node',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '',
})
export class ComarkNodeComponent implements OnChanges {
  /** The Comark AST node to render */
  @Input({ required: true }) node!: ComarkNode

  /** Custom component mappings */
  @Input() components: Record<string, Type<any>> = {}

  /** Render data for :binding resolution */
  @Input() renderData: NodeRenderData = { frontmatter: {}, meta: {}, data: {}, props: {} }

  /** Parent node (for context like `pre` tag detection) */
  @Input() parent?: ComarkNode

  constructor(
    private vcr: ViewContainerRef,
    private renderer: Renderer2,
    private elementRef: ElementRef,
    private injector: Injector
  ) {}

  ngOnChanges(_changes: SimpleChanges): void {
    this.render()
  }

  private render(): void {
    this.vcr.clear()

    const hostEl = this.elementRef.nativeElement as HTMLElement
    // Clear previous content from the host
    while (hostEl.firstChild) {
      hostEl.removeChild(hostEl.firstChild)
    }

    if (this.node === undefined || this.node === null) return

    // Text node
    if (typeof this.node === 'string') {
      const text = this.renderer.createText(this.node)
      this.renderer.appendChild(hostEl, text)
      return
    }

    // Element node
    if (Array.isArray(this.node)) {
      const tag = getTag(this.node)
      if (!tag) return

      const nodeProps = getProps(this.node)
      const children = getChildren(this.node)

      // Resolve custom component
      let customComponent: Type<any> | undefined

      if ((this.parent as ComarkElement | undefined)?.[0] !== 'pre') {
        if (nodeProps.as) {
          customComponent = resolveComponent(nodeProps.as, this.components)
        }
        if (!customComponent) {
          customComponent = resolveComponent(tag, this.components)
        }
      }

      // Resolve attributes (:binding support)
      const resolved = resolveAttributes(nodeProps, this.renderData, { parseJson: true })

      // Build childrenRenderData — only shadow parent scope when element has own attrs
      const hasOwnAttrs = Object.keys(resolved).length > 0
      const childrenRenderData: NodeRenderData = hasOwnAttrs ? { ...this.renderData, props: resolved } : this.renderData

      if (customComponent) {
        this.renderCustomComponent(customComponent, resolved, children, childrenRenderData)
      } else {
        this.renderNativeElement(tag, resolved, children, childrenRenderData)
      }
    }
  }

  /** Apply resolved attributes to a DOM element. */
  private applyAttributes(el: HTMLElement, attrs: Record<string, any>): void {
    for (const key in attrs) {
      const value = attrs[key]
      if (key === 'as' || key === 'innerHTML' || key === 'dangerouslySetInnerHTML') {
        continue
      } else if (key === 'className' || key === 'class') {
        this.renderer.setAttribute(el, 'class', String(value))
      } else if (key === 'style' && typeof value === 'string') {
        this.renderer.setAttribute(el, 'style', value)
      } else if (key === 'tabindex') {
        this.renderer.setAttribute(el, 'tabindex', String(value))
      } else if (typeof value === 'boolean') {
        if (value) this.renderer.setAttribute(el, key, '')
      } else if (value != null) {
        this.renderer.setAttribute(el, key, String(value))
      }
    }
  }

  /** Create a native DOM element with attributes and children, append to parent. */
  private renderNativeEl(
    parentEl: HTMLElement,
    tag: string,
    attrs: Record<string, any>,
    children: ComarkNode[],
    childrenRenderData: NodeRenderData
  ): void {
    const el = this.renderer.createElement(tag)
    this.applyAttributes(el, attrs)

    if (attrs['innerHTML'] != null) {
      el.innerHTML = attrs['innerHTML']
    } else if (!VOID_ELEMENTS.has(tag)) {
      this.renderChildren(el, children, childrenRenderData)
    }

    this.renderer.appendChild(parentEl, el)
  }

  private renderNativeElement(
    tag: string,
    attrs: Record<string, any>,
    children: ComarkNode[],
    childrenRenderData: NodeRenderData
  ): void {
    this.renderNativeEl(this.elementRef.nativeElement as HTMLElement, tag, attrs, children, childrenRenderData)
  }

  private renderCustomComponent(
    componentType: Type<any>,
    attrs: Record<string, any>,
    children: ComarkNode[],
    childrenRenderData: NodeRenderData
  ): void {
    // Separate slots from regular children
    const slots: Record<string, ComarkNode[]> = {}
    const regularChildren: ComarkNode[] = []

    for (const child of children) {
      if (child === undefined || child === null) continue

      const childTag = getTag(child)
      const childProps = getProps(child)

      if (childTag === 'template' && childProps) {
        let slotName: string | undefined

        if (childProps.name) {
          slotName = childProps.name
        } else {
          for (const pk in childProps) {
            if (pk.startsWith('v-slot:') || pk.startsWith('#')) {
              slotName = pk.startsWith('#') ? pk.substring(1) : pk.substring(7)
              break
            }
          }
        }

        if (slotName) {
          slots[slotName] = getChildren(child)
          continue
        }
      }

      regularChildren.push(child)
    }

    // Pre-render children into a temporary container so we can pass them as projectableNodes for Angular's <ng-content /> content projection
    const tempContainer = this.renderer.createElement('div')

    // Render regular children
    if (regularChildren.length > 0) {
      this.renderChildren(tempContainer, regularChildren, childrenRenderData)
    }

    // Render named slot "default" children too
    if (slots['default']) {
      this.renderChildren(tempContainer, slots['default'], childrenRenderData)
    }

    // Collect all rendered child nodes for the default slot
    const defaultSlotNodes: Node[] = Array.from(tempContainer.childNodes)

    // Build projectableNodes array — index 0 is the default <ng-content />
    const projectableNodes: Node[][] = [defaultSlotNodes]

    // Create the Angular component with projected content
    const componentRef = createComponent(componentType, {
      environmentInjector: this.injector.get(EnvironmentInjector),
      elementInjector: this.injector,
      projectableNodes,
    })

    // Set inputs
    const mirror = reflectComponentType(componentType)
    const inputNames = new Set(mirror?.inputs.map((i) => i.propName) || [])

    for (const key in attrs) {
      if (key === 'as') continue
      if (inputNames.has(key)) {
        componentRef.setInput(key, attrs[key])
      }
    }

    // Pass __node if the component accepts it
    if (inputNames.has('__node')) {
      componentRef.setInput('__node', this.node)
    }

    // Render non-default named slots into the component's host element
    for (const slotName in slots) {
      if (slotName === 'default') continue
      const slotEl = this.renderer.createElement('div')
      this.renderer.setAttribute(slotEl, 'slot', slotName)
      this.renderer.setStyle(slotEl, 'display', 'contents')
      this.renderChildren(slotEl, slots[slotName], childrenRenderData)
      this.renderer.appendChild(componentRef.location.nativeElement, slotEl)
    }

    // Attach to DOM and detect changes
    this.vcr.insert(componentRef.hostView)
    componentRef.changeDetectorRef.detectChanges()
  }

  /**
   * Render an array of ComarkNode children into a parent DOM element.
   * Each child gets its own `comark-node` component created dynamically.
   */
  private renderChildren(parentEl: HTMLElement, children: ComarkNode[], renderData: NodeRenderData): void {
    for (const child of children) {
      if (child === undefined || child === null) continue

      // For text nodes, insert directly
      if (typeof child === 'string') {
        const text = this.renderer.createText(child)
        this.renderer.appendChild(parentEl, text)
        continue
      }

      // For element nodes, recursively create ComarkNodeComponent
      if (Array.isArray(child)) {
        const childTag = getTag(child)
        if (!childTag) continue

        const childProps = getProps(child)
        const grandChildren = getChildren(child)

        // Resolve custom component for this child
        let customComponent: Type<any> | undefined
        if ((this.node as ComarkElement)?.[0] !== 'pre') {
          if (childProps.as) {
            customComponent = resolveComponent(childProps.as, this.components)
          }
          if (!customComponent) {
            customComponent = resolveComponent(childTag, this.components)
          }
        }

        if (customComponent) {
          const componentRef = this.vcr.createComponent(ComarkNodeComponent)
          componentRef.instance.node = child
          componentRef.instance.components = this.components
          componentRef.instance.renderData = renderData
          componentRef.instance.parent = this.node
          componentRef.changeDetectorRef.detectChanges()

          // Move the component's host element into the parent
          const nativeEl = componentRef.location.nativeElement as HTMLElement
          nativeEl.style.display = 'contents'
          this.renderer.appendChild(parentEl, nativeEl)
        } else {
          const resolved = resolveAttributes(childProps, renderData, { parseJson: true })
          const hasOwnAttrs = Object.keys(resolved).length > 0
          const childRenderData: NodeRenderData = hasOwnAttrs ? { ...renderData, props: resolved } : renderData
          this.renderNativeEl(parentEl, childTag, resolved, grandChildren, childRenderData)
        }
      }
    }
  }
}
